name: Cypress Tests
on:
  pull_request:
    branches:
#      Uncomment to run on main branch
#      - main
      - not-real
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup code
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/**/*
          build: yarn build
          start: yarn start
